### ISSUE TITLE
Experiencing vercel deployment problem

### ISSUE THREAD

**Issue by mwenku** [mwelwankuta/ssr-mwelwa.tk#1]
failing to deploy to vercel and netlify with below error

```sh

Error: Cannot find module '@sveltejs/app-utils/renderer'
--
19:35:26.400 | Require stack:
19:35:26.400 | - /vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js
19:35:26.400 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
19:35:26.400 | at Function.Module._load (internal/modules/cjs/loader.js:746:27)
19:35:26.401 | at Module.require (internal/modules/cjs/loader.js:974:19)
19:35:26.401 | at require (internal/modules/cjs/helpers.js:93:18)
19:35:26.401 | at Object.<anonymous> (/vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js:7:16)
19:35:26.401 | at Module._compile (internal/modules/cjs/loader.js:1085:14)
19:35:26.401 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
19:35:26.401 | at Module.load (internal/modules/cjs/loader.js:950:32)
19:35:26.401 | at Function.Module._load (internal/modules/cjs/loader.js:790:12)
19:35:26.401 | at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
19:35:26.415 | error Command failed with exit code 1.
19:35:26.415 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:35:26.431 | Error: Command "yarn run build" exited with 1


```

**Comment by mwenku** [comment]
loading...
